# Experiment configuration
save_name: "setnet_gait3d_experiment_128_1"
model_name: "SetNet"
work_dir: "runs/checkpoints"
plots_dir: "runs/plots"

# Dataset configuration
dataset: "Gait3D"
data_root: "D:/open_datasets/Gait3D/2D_Silhouettes_cycles"
index_csv: "inputs/sequences_gait3D_split.csv"
resolution: 64
frame_num: 25
num_workers: 4
pid_num: 3000
pid_shuffle: false
train_pid_num: 3000

# Model configuration
hidden_dim: 128  # Configurable output feature dimension
hard_or_full_trip: "hard"
margin: 0.3

# Training hyperparameters
lr: 0.0001
epochs: 1
batch_P: 2
batch_K: 1
total_iter: 1
restore_iter: 0
save_iter: 1
plot_iter: 1
