# Experiment configuration
save_name: "setnet_gait3d_experiment_256_1"
model_name: "SetNet"
work_dir: "runs/checkpoints"
plots_dir: "runs/plots"

# Dataset configuration
dataset: "Gait3D"
data_root: "D:/open_datasets/Gait3D/2D_Silhouettes_cycles"
index_csv: "inputs/sequences_gait3D_split.csv"
resolution: 64
frame_num: 25
num_workers: 4
pid_num: 3000
pid_shuffle: false
train_pid_num: 3000

# Model configuration
hidden_dim: 256  # Configurable output feature dimension
hard_or_full_trip: "hard"
margin: 0.5

# Training hyperparameters
lr: 0.0003
epochs: 25
batch_P: 8
batch_K: 4
total_iter: 100000
restore_iter: 0
save_iter: 100
plot_iter: 10
